# Generated by Django 5.2 on 2025-04-07 16:01

import products.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Monitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=100)),
                ('processor', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'products_monitor',
            },
        ),
        migrations.CreateModel(
            name='Notebook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('processor', models.CharField(max_length=100)),
                ('ram', models.PositiveIntegerField()),
                ('storage', models.PositiveIntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, upload_to=products.models.notebook_image_upload_to)),
            ],
            options={
                'db_table': 'products_notebook',
            },
        ),
    ]
