# Generated by Django 5.1.7 on 2025-03-23 13:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articles',
            options={'verbose_name': 'Товар', 'verbose_name_plural': 'Товары'},
        ),
        migrations.AddField(
            model_name='articles',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 23, 13, 31, 20, 670489, tzinfo=datetime.timezone.utc), verbose_name='Дата публикации'),
            preserve_default=False,
        ),
    ]
