# Generated by Django 5.1.7 on 2025-03-28 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_articles_options_articles_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='static/main/img/articles/', verbose_name='Изображение'),
        ),
    ]
