# Generated by Django 5.1.7 on 2025-03-28 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_articles_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='main/img/articles/', verbose_name='Изображение'),
        ),
    ]
